### ISSUE TITLE
new site

### ISSUE THREAD

**Issue by RobertKozak** [Cidney/Cidney.github.io#1]
I deleted the old repo because I messed it up. I'm really not that good at this :)

If you have time can you apply the Jekyll-Clean theme? Just clone this one: https://github.com/scotte/jekyll-clean. 

If you can't let me know and I'll figure something out in a week or two.

**Comment by mattmcnabb** [comment]
I can go ahead get the theme applied. Do you think it's ok to just get a point in time clone of the theme now, or would you rather have the ability to fetch from the original as it changes? I'd rather just do a simple clone and let the page morph on it's own as we see fit.

**Comment by RobertKozak** [comment]
Simple clone should be fine. I just want a place to get some samples up. If it works today it should be fine a year from now regardless of any changes in the original template.
